# See https://docs.redoc.ly/cli/configuration/ for more information.
apiDefinitions:
  main: openapi/openapi.yaml
lint:
  rules:
    no-unused-schemas: warning
referenceDocs:
  htmlTemplate: ./docs/preview.html
  theme:
    colors:
      primary:
        main: "#32329f"
