name: publish-design

# Publish of design versions happens on push to develop for now.
# (Once the multi-version docs go live, this will trigger off master.)
# Needs to include:
# * Design changes
# * Anything required to actually build a spec, e.g. scripts, package files:
#   not required immediately, but will be required when a spec is published
# In practice, anything besides the actual published specs themselves
on:
  push:
    branches:
      - develop
    paths-ignore:
      - docs/builds/*
      - docs/builds.json
      - docs/dist.yaml
jobs:
  build:
    if: github.repository == 'alaress/schoolbox-api-docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - uses: actions/checkout@v3
      - name: Push design to gh-pages branch
        id: publish-design
        run: |
          # Commit on behalf of the github-actions bot
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Copy all files (excl. builds/, builds.json, dist.yaml) into gh-pages repo
          mkdir .staging/
          cp -r ./* .staging/
          rm -rf .staging/docs/builds/
          rm -f .staging/docs/dist.yaml
          rm -f .staging/docs/builds.json
          git checkout gh-pages
          cp -r .staging/* .
          rm -rf .staging/

          # Commit and push
          git add .
          git commit -m "Build design for tag ${$GITHUB_REF}" .
          git push
